### PR TITLE
Fix README markdown header formatting

### PR DESCRIPTION
**Pull request by blahah**

### CODE REVIEW

**Comment by maplesond** [comment]
Actually, I've updated the README.md in the develop branch using a different formatting to what you suggested in the commit.  Please take a look and let me know if this works for you.

Best regards,
Dan

**Comment by blahah** [comment]
OK - sure. I was mainly trying to make the README render properly for people who land on the page - can your update be applied to master as well?

**Comment by maplesond** [comment]
Ok great.  I'll migrate the changes over to master with the next release.  Although, this may take a few weeks.

**Comment by bjclavijo** [comment]
Probably better to have the main README that people lands on fixed asap. This not being code change, it shouldn’t need a release.


Best,

bj

**Pull request closed without merging**
