### PR TITLE
Kmer spectra-cn plot --Ignore_absent <bool> to --min_assembly_frequency <int>

### PR DESCRIPTION
**Pull request by gonzalogacc**
Now the -i  can filter more than the erros, this is useful to isolate the other distributions in the spectra-cn plot.

### CODE REVIEW

**Comment by maplesond** [comment]
Hi Gonza.  Have you tried the latest change on the develop branch, which I sent it to Bernardo last week?

**Comment by gonzalogacc** [comment]
it's the same thing!
Disregard this!
Thanks!
Gonza.-

**Comment by maplesond** [comment]
Thanks @pavel-sakun and @gonzalogacc. I'll integrate these changes into the next release.

**Comment by maplesond** [comment]
Addressed in latest release.

**Pull request closed without merging**
